- src/utils/utils.test.ts
- src/utils/utils.ts
**Description**
If this project is run against a fresh Firebase RTDB project, the `deleteMissingKeysAndUpdate` function will fail when trying to enumerate the `current` tokensInfo in the following line
```ts
const currentKeys = Object.keys(current)
```
**Impact**
Users that intent to use this repo to create their own Firebase RTDB will not be able to write the initial tokensInfo set to the RTDB instance.
> Fix issue where `yarn update` fails for clean Firebase RTDB Instance

- .github/workflows/workflow.yaml
We now need the `google-github-actions/auth` action first.
See [failed action](https://github.com/valora-inc/address-metadata/actions/runs/4007265222/jobs/6879892191):
Tested successfully in https://github.com/valora-inc/address-metadata/actions/runs/4007356862/jobs/6880099011
> ci: fix gcloud auth

- src/data/mainnet/tokens-info.json
[We are not handling correctly](https://linear.app/valora/issue/RET-712/[wallet]-swapping-tokens-with-different-decimals-is-not-working) the `decimals` in the swap flow.
We should disable btc in the swap until the bug is fixed.
> fix(swaps): Disable swapping btc until decimals bug is fixed.

- src/data/mainnet/tokens-info.json
Disabling stCelo because it has low liquidity, offering really bad exchange rates.
> Disabling swaps with stcelo

- scripts/update-bq.ts
The script was defaulting to `us-central1` unlike all of our other data which is multi-region 'US'. Querying a single region table along with our other multiregion tables in a single query was causing some issues.
> chore(bq): upload to US region

- src/index.test.ts
- src/schemas/tokens-info.ts
- src/tokens-info.ts
- src/types.ts
- src/utils/transforms.ts
in the wallet, we will need some mapping from the network field to a subtitle to show in the transaction feed. if we want to show "Celo Alfajores Network" in the feed at some point as opposed to just "Celo Network" (particularly if we enable some "dev mode" in the future), we'll need information about the environment (testnet vs mainnet) as well as the network (eth vs celo vs ...). This PR updates TokenInfo to include that information by using an environment-specific networkId, rather than just "network".
> refactor(networkId): switch from network to networkId on TokenInfo type

- src/data/mainnet/celo-tokens-info.json
- src/data/testnet/celo-alfajores-tokens-info.json
- src/index.test.ts
- src/schemas.test.ts
As per the title this renames `Celo native asset` to simply `Celo`. With the incoming new address structure the existing name is redundant and not localized.
> chore: rename Celo native asset to Celo

- .github/workflows/workflow.yaml
- package.json
- src/index.test.ts
- src/index.ts
- src/schemas.test.ts
- src/tokens-info.ts
Deployment scripts are changed to deploy `getTokensInfoCF` as a [2nd gen](https://cloud.google.com/functions/docs/concepts/version-comparison) cloud function.
We noticed while implementing supercharge that cloud functions that call other cloud functions often incurs the cold start penalty. We observed a 5-6s performance impact.
While we don't know for sure what impact this will have, we know that this CF will be called for updating and retrieving token prices and it is low lift to make this optimisation already.
New name for cloud function is `getTokensInfo`. I's a replacement for a [deprecated function](https://github.com/valora-inc/valora-rest-api/pull/645) from `valora-rest-api`.
Note: Currently 2nd gen functions naming convention [do support uppercase letters and …
> chore: Make getTokensInfoCF 2nd gen cloud function

- src/index.test.ts
- src/schemas.test.ts
- src/schemas/tokens-info.ts
- src/tokens-info.ts
- src/types.ts
- src/utils/transforms.ts
* adds tokenId field to the get-token-info cloud function
* refactors to have separate types/schemas for the JSON tokenInfo and the Processed tokenInfo
Per feedback on https://github.com/valora-inc/blockchain-api/pull/336#discussion_r1338234104
> feat(get-tokens-info): add tokenId to tokenInfo

- src/data/testnet/celo-alfajores-tokens-info.json
eXOF is part of the listed fee currencies:
https://alfajores.celoscan.io/address/0xb8641365dbe943bc2fb6977e6fbc1630ef47db5a#readProxyContract
Enabling only on Alfajores for testing. Then we can do the same on mainnet if everything works.
Note: I checked it supports [transferWithComment](https://explorer.celo.org/alfajores/address/0xB0FA15e002516d0301884059c0aaC0F0C72b019D/write-proxy#address-tabs).
But I saw [G$](https://explorer.celo.org/alfajores/token/0x03d3daB843e6c03b3d271eff9178e6A96c28D25f/token-transfers) is also listed as a feeCurrency (only on alfajores), but doesn't support [transferWithComment](https://explorer.celo.org/alfajores/address/0x03d3daB843e6c03b3d271eff9178e6A96c28D25f/write-proxy#address-tabs) which means we should split isCoreToken into 2 things: …
> feat(token): enable eXOF usable as feeCurrency on alfajores

- src/data/testnet/ethereum-sepolia-tokens-info.json
I'm currently working on testing non-native ERC20 sends from the wallet, and was able to receive some Sepolia USDC from [this faucet](https://staging.aave.com/faucet/) hosted by Aave. (As a sidenote, this faucet seems to give a variety of useful testnet ERC20 tokens in large amounts -- good to use for testing purposes. In conjunction with Alchemy's [Sepolia ETH faucet](https://sepoliafaucet.com/), these should both cover a lot of our test cases.)
The USDC that I was given from this faucet is actually the contract [here](https://sepolia.etherscan.io/token/0x94a9d9ac8a22534e3faca9f4e7f2e2cf85d5e4c8). Compare the frequency of events on this contract to the one that Sepolia USDC is [currently set to](https://sepolia.etherscan.io/address/0x8267cf9254734c6eb452a7bb9aaf97b392258b21). Updating …
> Update address of Sepolia USDC

- src/data/mainnet/celo-tokens-info.json
...was impacted by the Multichain hack, so let's prevent people from swapping into CRV. (There's also very few txs total on CELO over the last 100 days).
> chore: disable CRV swapping

- scripts/update-bq.ts
Adds Ethereum tokens from to the `address_metadata.tokens_info` in Big Query. The table should be edited to include the following nullable fields: `tokenId` and `networkId`.
ACT-953
> feat: populate multiple chains in big query tokenInfo table

- src/data/mainnet/ethereum-tokens-info.json
- src/data/testnet/ethereum-sepolia-tokens-info.json
ETH was not marked as `cashInEligible` so was not showing up on the new CICO token bottom sheet, now it should.
> chore: make ETH cash-in eligible

- src/data/mainnet/ethereum-tokens-info.json
- src/data/testnet/ethereum-sepolia-tokens-info.json
We have added support for the following:
USDC: Simplex, Ramp, Moonpay, CBPay, Bitmama, Fonbnk
USDT: Simplex, Ramp, Moonpay, CBPay, Bitmama
https://linear.app/valora/issue/ACT-1015/update-address-metadata-for-usdcandt-cico
Will test on Testflight
> chore(cash-in): add USDT and USDC as cash-in tokens

- src/data/mainnet/arbitrum-one-tokens-info.json
- src/data/testnet/arbitrum-sepolia-tokens-info.json
- src/schemas.test.ts
- src/schemas/tokens-info.ts
- src/tokens-info.ts
- src/types.ts
- src/utils/transforms.ts
and require network icon URLs for L2 native tokens, and stop using the native token as the network icon (for arbitrum this doesn't work since the native token is ETH, but the network icon should be the same as ARB)
> feat(arbitrum): add arbitrum-one, arbitrum-sepolia

- src/data/testnet/celo-alfajores-tokens-info.json
- src/schemas/tokens-info.ts
When an adapter is needed, the token address can't be used directly as a fee currency.
In order to be backward compatible, we must leave `isFeeCurrency: false` or not set it.
See Slack [thread](https://valora-app.slack.com/archives/C029Z1QMD7B/p1707907378255969?thread_ts=1707835925.846589&cid=C029Z1QMD7B) for context.
Fixes RET-1009
> fix: ensure `isFeeCurrency` is `false` or not set when `feeCurrencyAdapterAddress` is set

- src/data/testnet/celo-alfajores-tokens-info.json
This is the latest adapter to use which works: https://alfajores.celoscan.io/tx/0x22613488f35616f1db2fc2cbd8d0b2227b1568c63a31e8ccb88f6a828acf3b04
> chore: update STBLTEST adapter address

- scripts/update-bq.ts
Adding the `NetworkId` for `arbitrum-one` and `op-mainnet` in order to import tokens for these two chains into the address_metadata.tokens_info table in BigQuery. We will then be able to use this table to filter on the tokens for those two chains when we pull transfers into `valora_user_transfers`.
> Add Arbitrum and Optimism to tracked tokens in address_metadata.tokens_info

- src/data/mainnet/celo-tokens-info.json
- src/data/testnet/celo-alfajores-tokens-info.json
Ubeswap is moving to a new contract address: [info](https://app.ubeswap.org/#/claim-new-ube) & [slack thread request](https://valora-app.slack.com/archives/C029Z1QMD7B/p1711053443782269).
> New Tokenomics
Ubeswap has migrated to new token economics.
All token swaps made until April 15th 2024 will be made on a 1:1,5 basis. After this period, it will switch to 1:1. After 75% of the liquid tokens are swapped, 1 month will be provided for the remainder of the community to swap. Any tokens not swapped after this period will be burned.
Used Ubeswaps conversation tool and verified the [transaction on CeloScan](https://celoscan.io/tx/0x154ff71d0bdacacdb16231e1cb18ff9405b6c49c8fb6314e095efdbaafda8165).
> chore: update ubeswap

- src/data/testnet/celo-alfajores-tokens-info.json
Follow up to #441 using the old address for UBE on Alfajores to fix an issue described in [this comment](https://github.com/valora-inc/address-metadata/pull/441#discussion_r1547441287).
> fix: use old ube address on alfajores

- src/data/mainnet/polygon-pos-tokens-info.json
Adds the minimum swap version for polygon tokens to enable swaps in the wallet.
> chore: add minimum swap version for polygon tokens

- src/data/mainnet/polygon-pos-tokens-info.json
- src/data/testnet/polygon-pos-mumbai-tokens-info.json
- src/schemas/tokens-info.ts
MATIC's contract doesn't have standard ERC-20 methods and it's causing issues with our swaps. As a solution I've removed the address to allow it to be treated similar to other native tokens such as ETH.
ACT-1124
> fix: remove matic address with no approval method

- src/data/mainnet/base-tokens-info.json
- src/data/mainnet/polygon-pos-tokens-info.json
Make MATIC and USDC cash in eligible on polygon mainnet, ETH and USDC cash in eligible on base mainnet.
> feat(multichain): Make polygon and base tokens cash-in eligible

- src/data/testnet/arbitrum-sepolia-tokens-info.json
Took this from the Aave sepolia contract https://github.com/bgd-labs/aave-address-book/blob/8e1ffb3499fdcde5941cf03ae42547f68ce25cad/src/AaveV3ArbitrumSepolia.sol#L89
> fix(tokens): use the right usdc on arb sepolia

- src/data/testnet/arbitrum-sepolia-tokens-info.json
Adds Aave Arbitrum Sepolia USDC - https://sepolia.arbiscan.io/token/0x460b97BD498E1157530AEb3086301d5225b91216.
> chore: add aave arbitrum sepolia usdc

- src/data/mainnet/celo-tokens-info.json
impactMarket is migrating to the new PACT token
listing it in the same way [it was done for UBE](https://github.com/valora-inc/address-metadata/blob/ba7fe596ee06b3cccfdce16bf64e8bf182eb93a3/src/data/mainnet/celo-tokens-info.json#L19-L35) (#441)
context: 
* https://valora-app.slack.com/archives/C02UAE4MGUF/p1718292393805179
* https://twitter.com/impactmarket/status/1800620301996236866
* https://app.ubeswap.org/#/claim-new-pact
> chore: add new PACT token

- src/data/mainnet/arbitrum-one-tokens-info.json
This is temporary, once we have a AAVE position hook, we won't need to manually add these.
https://arbiscan.io/address/0xe50fA9b3c56FfB159cB0FCA61F5c9D750e8128c8
> chore: add aArbWETH

- README.md
- scripts/add-erc20-tokens-coingecko.ts
Previously we were making requests to coingecko for each token to get the token address, which results in some necessary sleeps to avoid rate limiting. This PR fetches all tokens upfront so we only need to make 2 requests to coingecko per chain, which makes the script run much faster. + also make new tokens swappable by default.
> feat: improve speed of bulk token add script

- src/data/mainnet/addresses-extra-info.json
Axelar Gas Service address is used to refund excessive cross-chain gas fees.
The address `0x2d5d7d31f671f86c782533cc367f14109a082712` is the same across all supported networks (see `axelarContracts` in Squid API `/chains` return values: https://squidrouter.readme.io/reference/get_chains)
Example tx: https://celoscan.io/tx/0x0a460f22636d6b1714bb537d2e7a34b7fc6880513cdf9544d2490c52df440692
Context: https://valora-app.slack.com/archives/C0684TXDR3K/p1721937744043559?thread_ts=1721316010.808989&cid=C0684TXDR3K
> feat(addresses-extra-info): add a friendly name for axelar gas service

- src/data/mainnet/celo-tokens-info.json
cKES was not showing up for cash-in when filtering by stablecoins. This should fix.
> chore: Mark cKES as stablecoin

- src/data/mainnet/celo-tokens-info.json
Adds additional fields to  cCOP (Celo Colombian Peso):
- `isFeeCurrency: true` - this is a cStable.
- `canTransferWithComment: true` - same as above.
-  `minimumAppVersionToSwap: 1.68.0` - so that cCOP appears as an available swap to token.
> fix(ccop): add additional details

- src/data/mainnet/arbitrum-one-tokens-info.json
- src/schemas/tokens-info.ts
Part of [ACT-1404](https://linear.app/valora/issue/ACT-1404/dont-show-aave-pool-token-on-token-list-version-=196)
> chore(aave): Add maxSupportedVersion for valora for Aave Arbitrum USDCn

- src/data/mainnet/arbitrum-one-tokens-info.json
use same maxSupportedVersion as Aave token (conversation [here](https://valora-app.slack.com/archives/C03D3K379FE/p1731355946156189))
Setting it for tokens added in [this PR](https://github.com/valora-inc/address-metadata/pull/504), and the following PRs from Jean:
- https://github.com/valora-inc/address-metadata/pull/519
- https://github.com/valora-inc/address-metadata/pull/487
- https://github.com/valora-inc/address-metadata/pull/486
> chore: add maxSupportedVersion for Troopo tokens
