src/data/mainnet/tokens-info.json

update PLASTIK token address

---

src/data/mainnet/tokens-info.json

chore: add optics v2 USDC

---

src/data/mainnet/addresses-extra-info.json

chore: add invite rewards wallet label

---

package.json
src/data/mainnet/tokens-info.json
src/schemas/tokens-info.ts
yarn.lock

Adding a `minimumAppVersionToSwap ` flag, this will allow us to add new tokens to the swap screen for specific releases (leaving the old releases intact if we want) without any extra code change.

feat(swaps): Adding swap versioning

---

src/data/mainnet/tokens-info.json

In Valora version `1.60.0`, we added a warning message in case the return exchange rate from 0x is "bad".
This allow us to enable more tokens that have less liquidity.
Context: https://linear.app/valora/issue/RET-745/update-swapped-asset-support

chore(swaps): Enabling tokens in the swap flow

---

src/data/mainnet/tokens-info.json

* Disabling btc from optics
* Enabling btc from wrapped.com

Fixing wrapped btc for swaps

---

.gcloudignore
.github/workflows/workflow.yaml
config-dev.yaml
config-prod.yaml
package.json
scripts/diff.ts
scripts/update-rtdb.ts
src/clients/firebase-client.ts
src/config.ts
src/index.test.ts
src/index.ts
src/log.ts
src/schemas.test.ts
src/types.ts
src/wrap.test.ts
src/wrap.ts
yarn.lock

https://linear.app/valora/issue/ACT-908/createupdate-cloud-function-to-return-new-tokens-info
tested by deploying from local machine and invoking from GCP console https://console.cloud.google.com/functions/details/us-central1/getTokensInfoCF?env=gen1&hl=en&project=celo-mobile-alfajores&tab=testing

feat(cloud-function): getTokensInfoCF

---

src/data/mainnet/celo-tokens-info.json

Checked against [celo scan](https://celoscan.io/token/0x97926a82930bb7b33178e3c2f4ed1bfdc91a9fbf)

feat(tokens): Identifying dai from wormhole

---

src/data/mainnet/celo-tokens-info.json
src/schemas.test.ts
src/schemas/tokens-info.ts
src/types.ts
src/utils/transforms.test.ts
src/utils/transforms.ts

Moving bridge information to its own field (removing it from the token name).
Adding the bridge in the token name only when pushing to firebase.

feat(token-list): Adding bridge field

---

src/data/mainnet/celo-tokens-info.json

Only merge this PR once the buy flow has been disabled for all users.

feat(swap): Enabling token that don't work with 0x

---

.github/workflows/workflow.yaml
package.json
scripts/update-bq.ts

Updates our existing GitHub workflow to update the big query tables on merges to main. Failures of this script now exit with failed with exit code 1.
ACT-929

feat: update token info in big query on merges to main

---

src/data/mainnet/ethereum-tokens-info.json

feat: make ETH and USDC swappable

---

src/data/testnet/celo-alfajores-tokens-info.json
src/schemas/tokens-info.ts
src/types.ts

Prepare for fee currency adapters.
And added a token using it on Celo Alfajores.
Fixes RET-1009

feat: add `feeCurrencyAdapterAddress` and `feeCurrencyAdapterDecimals`

---

src/data/mainnet/celo-tokens-info.json
src/data/testnet/celo-alfajores-tokens-info.json

https://valora-app.slack.com/archives/C029Z1QMD7B/p1708457797557289

chore: add USDC

---

src/data/testnet/celo-alfajores-tokens-info.json

Was just added to the whitelist on Alfajores:
https://alfajores.celoscan.io/address/0xB8641365dBe943Bc2fb6977e6FBc1630EF47dB5a#readProxyContract

feat: USDC fee currency adapter on Alfajores

---

src/data/testnet/ethereum-sepolia-tokens-info.json

feat: enable cashout for ETH sepolia assets

---

src/data/mainnet/ethereum-tokens-info.json

Per product's request https://valora-app.slack.com/archives/C03D3K379FE/p1711404950458749?thread_ts=1711403904.559589&cid=C03D3K379FE, will merge this after #431 and testing it

feat: enable cashout for ETH assets

---

src/data/mainnet/arbitrum-one-tokens-info.json

Adds aArbUSDCn on Arbitrum: [Token details](https://arbiscan.io/token/0x724dc807b04555b71ed48a6896b6f41593b8c637).
Fixed ACT-1184

chore: add aArbUSDCn

---

src/data/testnet/arbitrum-sepolia-tokens-info.json

Will be useful for earn MVP development

feat(tokens): add usdc to arb sepolia

---

src/data/mainnet/arbitrum-one-tokens-info.json

Temporarily adding it here, but the end goal is to use positions, this way we can have proper pricing for this pool.
https://arbiscan.io/address/0x845c8bc94610807fcbab5dd2bc7ac9dabaff3c55

chore: add TriCRV-ARBITRUM from Curve

---

src/data/mainnet/optimism-tokens-info.json

I inadvertently removed one prop in #482 when I resolved the conflict.

fix: wrong merge in #482

---

src/data/mainnet/arbitrum-one-tokens-info.json

https://arbiscan.io/token/0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f

chore: add WBTC on Arbitrum

---

src/data/mainnet/arbitrum-one-tokens-info.json
src/data/mainnet/base-tokens-info.json
src/data/mainnet/ethereum-tokens-info.json
src/data/mainnet/optimism-tokens-info.json

feat: make all tokens on non-Celo networks swappable

---

src/data/mainnet/celo-tokens-info.json

From the conversation here: https://valora-app.slack.com/archives/C02KBT0DAHJ/p1724890479108329

feat(cico): Make cKES cash in eligible

---

src/data/mainnet/arbitrum-one-tokens-info.json
src/data/mainnet/celo-tokens-info.json
src/data/mainnet/ethereum-tokens-info.json
src/data/mainnet/optimism-tokens-info.json
src/data/testnet/ethereum-sepolia-tokens-info.json

> USD₮, EUR₮, MXN₮, CNH₮, XAU₮
> Crypto USD, EUR, MXN, CNH and gold. USD₮, EUR₮, MXN₮ and CNH₮ are issued by Tether Operations Limited. XAU₮ is issued by TG Commodities Limited. Similar to bitcoin utilizing the Unicode symbol ₿, Tether tokens are represented by the Unicode symbol ₮ (Tugrik sign).
Source: https://tether.io/media/
Also see this Slack [thread](https://valora-app.slack.com/archives/C025Q9QG8JG/p1726058421841199?thread_ts=1725637260.916179&cid=C025Q9QG8JG).

chore: update USDT symbol to USD₮

---

src/data/mainnet/addresses-extra-info.json

This helps with mobilestack, [context](https://valora-app.slack.com/archives/C025Q9QG8JG/p1727366548592999)

chore: make gas refund name generic

---

src/data/mainnet/celo-tokens-info.json

chore(ckes): Make ckes cash out eligible

---

src/data/mainnet/base-tokens-info.json

[Slack Thread](https://valora-app.slack.com/archives/C0257HQBWF8/p1732570440506979) - Adds the following tokens:
- [Blonde (BLONDE)](https://basescan.org/token/0x28bc44f9754f590da1564c1a7ba35f8e1d1b134a)
- [BRUNETTE (BRUNETTE)](https://basescan.org/token/0x34c990ee5aa627e9304234cc59b0734163eac06b)

chore: add Blonde and BRUNETTE tokens on Base
